## 1. Creating Arrays

In [1]:
import numpy as np

In [2]:
# 1D
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
# 2D
b = np.array([[1,2,3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Array of zeros
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Array of ones
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# Array with a range of values
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [10]:
# Array with evenly spaced values
linspace_array = np.linspace(0, 1, 5)
linspace_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## 2.Array Attributes

In [11]:
print(a.shape)

(3,)


In [12]:
print(b.ndim)

2


In [14]:
print(b.dtype)

int32


## 3. Basic Operations

In [15]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [16]:
# Element-wise addition
print(x+y)

[5 7 9]


In [17]:
# Element-wise multiplication
print(x * y)

[ 4 10 18]


In [18]:
# Universal functions
print(np.sqrt(x))

[1.         1.41421356 1.73205081]


## 4. Indexing and Slicing

In [19]:
arr = np.array([[1,2,3], [4,5,6]])

In [20]:
# Accessing elements
print(arr[0, 1])

2


In [21]:
# Slicing
print(arr[:, 1])

[2 5]


In [66]:
# Fancy indexing
a = np.array([10, 20, 30, 40])
print(a[[0, 2]])  # Output: [10 30]

[10 30]


In [67]:
# Negative indexing
print(a[-1])  # Output: 40

40


## 5. Boolean Masking

In [23]:
mask = arr > 3
print(arr[mask])

[4 5 6]


## 6. Reshaping Array

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
reshaped = arr.reshape((3,2))
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

## 7. Stacking Array 

In [26]:
a = np.array([1,2])
b = np.array([3,4])

In [27]:
# Vertical stack
print(np.vstack((a, b)))

[[1 2]
 [3 4]]


In [28]:
# Horizontal stack
print(np.hstack((a, b)))

[1 2 3 4]


## 8. Splitting Array

In [3]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.hsplit(x, 3)    # Split into 3 columns
np.vsplit(x, 2)    # Split into 2 rows

[array([[1, 2, 3]]), array([[4, 5, 6]])]

## 9. Broadcasting

In [32]:
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
print(a, 'next')
print(b)

[1 2 3] next
[[4]
 [5]
 [6]]


In [33]:
# Broadcasting addition
print(a + b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


## 10. Linear Algebra Operations

In [34]:
from numpy.linalg import inv, eig, svd

In [35]:
matrix = np.array([[1,2], [3,4]])
matrix

array([[1, 2],
       [3, 4]])

In [36]:
# Inverse
print(inv(matrix))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [37]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = eig(matrix)

In [39]:
print(eigenvalues)

[-0.37228132  5.37228132]


In [40]:
print(eigenvectors)

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [41]:
# Singular Value Decomposition
U, S, V = svd(matrix)

In [43]:
print(U)

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]


In [44]:
print(S)

[5.4649857  0.36596619]


In [45]:
print(V)

[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [90]:
# Matrix Multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = a @ b
c

array([[19, 22],
       [43, 50]])

In [91]:
# or 
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [93]:
# Matrix Inverse & Determinant
from numpy.linalg import inv, det
inv_a = inv(a)
inv_a

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [94]:
det_a = det(a)
det_a

-2.0000000000000004

In [95]:
# Solve Linear Systems
from numpy.linalg import solve
x = solve(a, np.array([1, 0]))

In [96]:
x

array([-2. ,  1.5])

## 11. Random Number Generation

In [46]:
# Random floats in [0.0, 1.0]
random_floats = np.random.rand(3,2)

In [47]:
random_floats

array([[0.84618559, 0.26906208],
       [0.58278334, 0.61929993],
       [0.99855344, 0.12834408]])

In [58]:
# Random integers b/w 0 and 20
random_integers = np.random.randint(0, 20, size= (3,2))

In [59]:
random_integers

array([[16, 11],
       [12, 15],
       [ 7, 14]])

In [97]:
# Generate Random Values
import numpy as np

In [98]:
np.random.rand(2, 3)     # Uniform [0, 1)

array([[0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [99]:
np.random.randn(2, 3)    # Standard normal

array([[-0.57138017, -0.92408284, -2.61254901],
       [ 0.95036968,  0.81644508, -1.523876  ]])

In [100]:
np.random.randint(1, 10, size=(2, 3))  # Integers

array([[3, 7, 4],
       [9, 3, 5]])

In [101]:
# Random Choice
np.random.choice([10, 20, 30], size=5, p=[0.1, 0.3, 0.6])

array([30, 20, 10, 30, 30])

In [105]:
# Shuffle and Permutation
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
np.random.shuffle(a)         # In-place

In [104]:
a

array([0, 5, 2, 6, 3, 7, 4, 9, 8, 1])

In [107]:
np.random.permutation(a)     # Returns new array
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
# Setting seed for reproducibility
np.random.seed(42)

## 12. Normalize Rows of a Matrix

In [61]:
def normalize_rows(x):
    return x / np.linalg.norm(x, axis=1, keepdims=True)

matrix = np.random.rand(3, 3)
normalized_matrix = normalize_rows(matrix)
print(normalized_matrix)

[[0.29797254 0.75635891 0.58235175]
 [0.93830842 0.24453609 0.24449828]
 [0.05500741 0.82030212 0.56927903]]


## 13. Custom Universal Function

In [63]:
# Define a custom function
def custom_func(x):
    return x**2 + 2*x + 1

#Vectorize the function
vectorized_func = np.vectorize(custom_func)

#Apply to array
arr = np.array([1, 2, 3])
print(vectorized_func(arr))
#Output: [4 9 16]

[ 4  9 16]


## 14. Memory Efficiency: Views vs. Copies

In [64]:
a = np.arange(10)
b = a[::2]  # This is a view
b[0] = 100
print(a)    # Output: [100   1   2   3   4   5   6   7   8   9]

[100   1   2   3   4   5   6   7   8   9]


## 15. Advanced Indexing


In [65]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

#Select elements at positions (0,1), (1,0), and (2,1)
indices = ([0, 1, 2], [1, 0, 1])
print(arr[indices])  # Output: [2 3 6]

[2 3 6]


## 16. Vectorization

In [72]:
# Loop
a = [1, 2, 3, 4]
b = [x**2 for x in a]

In [69]:
a

[1, 2, 3, 4]

In [71]:
b

[1, 4, 9, 16]

In [73]:
# Vectorization
import numpy as np
a = np.array([1, 2, 3, 4])
b = a ** 2  # Vectorized

In [74]:
a

array([1, 2, 3, 4])

In [75]:
b

array([ 1,  4,  9, 16])

In [76]:
%timeit [x**2 for x in range(100000)]        # Slower
%timeit np.arange(100000) ** 2               # Faster

76.6 ms ± 2.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
302 µs ± 12.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## 17. C-order vs Fortran-order   

In [82]:
a = np.array([[1, 2], [3, 4]], order='C')
a

array([[1, 2],
       [3, 4]])

In [83]:
b = np.array([[1, 2], [3, 4]], order='F')
b

array([[1, 2],
       [3, 4]])

In [84]:
# view(): Shares memory   
b = a.view()
b

array([[1, 2],
       [3, 4]])

In [85]:
# copy(): Independent data
c = a.copy()
c

array([[1, 2],
       [3, 4]])

## 18. Memory Info

In [86]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [87]:
# nbytes: Total bytes consumed     
print(a.nbytes)      # Total memory

16


In [88]:
# strides: Steps (in bytes) to move in each dimension
print(a.strides)     # e.g., (16, 8)

(8, 4)
